import { appendEvent, getCase, setCaseStatus } from "@/lib/ledger";
import { escalationLetter, traceSummary } from "@/lib/traceroute";
export const AGENT_ACTIONS = ["INTERPRET_STATE", "DRAFT_REBUTTAL", "FILE_APPEAL", "CHECK_SLA", "ESCALATE"] as const;
export type AgentAction = (typeof AGENT_ACTIONS)[number];
export interface AgentResult { action: AgentAction; summary: string; detail: string; completed: boolean; }
export function nextAgentStep(): AgentResult {
  const caseRecord = getCase(); if (!caseRecord) throw new Error("Synthetic case not found"); const types = new Set(caseRecord.events.map((entry) => entry.type));
  if (!types.has("FALSE_REJECTION_PROVEN")) { appendEvent("agent", "FALSE_REJECTION_PROVEN", { field: "name", left: caseRecord.facts.nameAsPerEmployer, right: caseRecord.facts.nameAsPerAadhaar, result: "MATCH" }); return { action: "INTERPRET_STATE", summary: "False rejection proven", detail: "The portal claims a mismatch; the independently verified member-ID and primary-UAN names are both Arjun Kumar.", completed: false }; }
  if (!types.has("REBUTTAL_DRAFTED")) { appendEvent("agent", "REBUTTAL_DRAFTED", { subject: "Request for reversal of false name-mismatch rejection", evidence: "Verified names match in hash-chained ledger" }); return { action: "DRAFT_REBUTTAL", summary: "Evidence-backed rebuttal drafted", detail: "The draft cites matching-name evidence and requests a written disposition.", completed: false }; }
  if (!types.has("APPEAL_FILED")) { appendEvent("agent", "APPEAL_FILED", { channel: "Escalation route", closureGap: "Grievance rejected its own tracking ID" }); return { action: "FILE_APPEAL", summary: "Appeal route opened", detail: "The agent records the invalid-tracking-ID closure gap rather than retrying the locked grievance form.", completed: false }; }
  if (!types.has("SLA_BREACH_CALCULATED")) { const sla = traceSummary(); appendEvent("agent", "SLA_BREACH_CALCULATED", { daysOverdue: sla.daysOverdue, compensationAccrued: sla.tatCompensationAccrued, ratePerDay: 100 }); return { action: "CHECK_SLA", summary: `SLA breach: ${sla.daysOverdue} days overdue`, detail: `The clock records ₹${sla.tatCompensationAccrued.toLocaleString("en-IN")} at ₹100/day for the overdue period.`, completed: false }; }
  if (!types.has("ESCALATION_SENT")) { appendEvent("agent", "ESCALATION_SENT", { addressee: traceSummary().blocker.designation, letter: escalationLetter() }); appendEvent("system", "CASE_RESOLVED", { resolution: "Synthetic escalation packet prepared and routed" }); setCaseStatus("RESOLVED"); return { action: "ESCALATE", summary: "Escalation packet routed", detail: "The accountable blocking node is named, the evidence bundle is chained, and the synthetic case is ready for disposition.", completed: true }; }
  return { action: "ESCALATE", summary: "Case already resolved", detail: "Restart the demo to replay the evidence trail.", completed: true };
}
