export interface TraceNode { id: string; office: string; designation: string; statutoryDeadlineDays: number; daysHeld: number; rule: string; breached: boolean; }
export const CASE_TRACE: TraceNode[] = [
  { id: "portal", office: "Member Portal", designation: "Automated eligibility engine", statutoryDeadlineDays: 1, daysHeld: 7, rule: "Claim intake and automated validation", breached: true },
  { id: "field", office: "Field Office", designation: "Accounts Officer", statutoryDeadlineDays: 7, daysHeld: 12, rule: "Claim verification queue", breached: true },
  { id: "regional", office: "Regional Office", designation: "Regional PF Commissioner", statutoryDeadlineDays: 15, daysHeld: 41, rule: "Disposition and grievance supervision", breached: true },
  { id: "cpc", office: "Central Processing Centre", designation: "Zonal Additional CPFC", statutoryDeadlineDays: 30, daysHeld: 0, rule: "Escalation destination", breached: false }
];
export const SLA_COMPENSATION_PER_DAY = 100;
export function traceSummary() { const blocker = CASE_TRACE.find((node) => node.id === "regional")!; const daysOverdue = blocker.daysHeld - blocker.statutoryDeadlineDays; return { nodes: CASE_TRACE, blocker, daysOverdue, tatCompensationAccrued: daysOverdue * SLA_COMPENSATION_PER_DAY }; }
export function escalationLetter() { const { blocker, daysOverdue, tatCompensationAccrued } = traceSummary(); return `To: ${blocker.designation}, ${blocker.office}\n\nSubject: Escalation — synthetic case SYN-EPFO-001\n\nThe independent case ledger records a false name-mismatch rejection although both verified records state “Arjun Kumar”. The case has remained at ${blocker.office} for ${blocker.daysHeld} days, ${daysOverdue} days beyond its ${blocker.statutoryDeadlineDays}-day handling window. Please issue a written disposition and reopen the grievance path. The demo SLA clock records ₹${tatCompensationAccrued.toLocaleString("en-IN")} at ₹100/day for the overdue period.\n\nThis is a synthetic demonstration draft; verify applicable rules before use.`; }
